version: "3"

services:
  back:
    build:
      context: ./backend
      target: deploy
    restart: always
    ports:
      - 8080:8080
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  front:
    build:
      context: ./frontend
    restart: always
    ports:
      - 80:3000
    environment:
      NODE_ENV: production
